PoketraVy-frontoffice/Models/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PoketraVy_frontoffice.Models
{
    public class ChangePasswordViewModel
    {
        public string Username { get; set; }
        public string NewPassword { get; set; }
        public string ConfirmPassword { get; set; }
    }
}

PoketraVy-frontoffice/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PoketraVy_frontoffice.Models
{
    public class LoginViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

PoketraVy-frontoffice/Controllers/CategorieUtilisateurBudgetController.cs
using Microsoft.AspNetCore.Mvc;
using PoketraVy_frontoffice.Data;
using PoketraVy_frontoffice.Models;
using System.Collections.Generic;
using System.Security.Claims;
using System;

namespace PoketraVy_frontoffice.Controllers
{
    public class CategorieUtilisateurBudgetController : Controller
    {
        private readonly CategorieUtilisateurBudgetRepository _categorieUtilisateurBudgetRepository;
        private readonly BudgetRepository _budgetRepository;

        public CategorieUtilisateurBudgetController(CategorieUtilisateurBudgetRepository categorieUtilisateurBudgetRepository,
            BudgetRepository budgetRepository)
        {
            _categorieUtilisateurBudgetRepository = categorieUtilisateurBudgetRepository;
            _budgetRepository = budgetRepository;
        }

        // GET: CategorieUtilisateurBudget
        public IActionResult Index()
        {
            IEnumerable<CategorieUtilisateurBudget> categorieUtilisateurBudgets = _categorieUtilisateurBudgetRepository.GetAll();
            return View(categorieUtilisateurBudgets);
        }

        // GET: CategorieUtilisateurBudget/Details/5
        public IActionResult Details(int id)
        {
            CategorieUtilisateurBudget categorieUtilisateurBudget = _categorieUtilisateurBudgetRepository.GetById(id);
            if (categorieUtilisateurBudget == null)
            {
                return NotFound();
            }
            return View(categorieUtilisateurBudget);
        }

        // GET: CategorieUtilisateurBudget/Create
        public IActionResult Create()
        {
            int userId = Int32.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var activeBudgets = _budgetRepository.GetActiveBudgetsByIdUser(userId);

            var viewModel = new CategorieUtilisateurBudgetCreationViewModel
            {
                ActiveBudgets = (List<Budget>)activeBudgets
            };

            return View(viewModel);
        }

        // POST: CategorieUtilisateurBudget/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategorieUtilisateurBudget categorieUtilisateurBudget)
        {
            if (ModelState.IsValid)
            {
                _categorieUtilisateurBudgetRepository.Add(categorieUtilisateurBudget);
                return RedirectToAction(nameof(Index));
            }
            return View(categorieUtilisateurBudget);
        }

        // GET: CategorieUtilisateurBudget/Edit/5
        public IActionResult Edit(int id)
        {
            CategorieUtilisateurBudget categorieUtilisateurBudget = _categorieUtilisateurBudgetRepository.GetById(id);
            if (categorieUtilisateurBudget == null)
            {
                return NotFound();
            }
            return View(categorieUtilisateurBudget);
        }

        // POST: CategorieUtilisateurBudget/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CategorieUtilisateurBudget categorieUtilisateurBudget)
        {
            if (id != categorieUtilisateurBudget.ID)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                _categorieUtilisateurBudgetRepository.Update(categorieUtilisateurBudget);
                return RedirectToAction(nameof(Index));
            }
            return View(categorieUtilisateurBudget);
        }

        // GET: CategorieUtilisateurBudget/Delete/5
        public IActionResult Delete(int id)
        {
            CategorieUtilisateurBudget categorieUtilisateurBudget = _categorieUtilisateurBudgetRepository.GetById(id);
            if (categorieUtilisateurBudget == null)
            {
                return NotFound();
            }
            return View(categorieUtilisateurBudget);
        }

        // POST: CategorieUtilisateurBudget/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _categorieUtilisateurBudgetRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

PoketraVy-frontoffice/Controllers/UtilisateurController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PoketraVy_frontoffice.Data;
using PoketraVy_frontoffice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PoketraVy_frontoffice.Controllers
{
    public class UtilisateurController : Controller
    {

        private readonly UtilisateurRepository _utilisateurRepository;
        private readonly UtilisateurBudgetRepository _utilisateurBudgetRepository;
        private readonly CategorieUtilisateurBudgetRepository _categorieUtilisateurBudgetRepository;
        private readonly MouvementRepository _mouvementRepository;

        public UtilisateurController(UtilisateurRepository utilisateurRepository,
            UtilisateurBudgetRepository utilisateurBudgetRepository,
            CategorieUtilisateurBudgetRepository categorieUtilisateurBudgetRepository,
            MouvementRepository mouvementRepository)
        {
            _utilisateurRepository = utilisateurRepository;
            _utilisateurBudgetRepository = utilisateurBudgetRepository;
            _categorieUtilisateurBudgetRepository = categorieUtilisateurBudgetRepository;
            _mouvementRepository = mouvementRepository;
        }

        // GET: UtilisateurController
        public ActionResult Index()
        {
            var users = _utilisateurRepository.GetAllUtilisateurs();
            return View(users);
        }

        // GET: UtilisateurController/Details/5
        public ActionResult Details(int id)
        {
            var utilisateur = _utilisateurRepository.GetById(id);
            if (utilisateur == null)
            {
                return NotFound();
            }

            return View(utilisateur);
        }

        // GET: UtilisateurController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UtilisateurController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Utilisateur utilisateur)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _utilisateurRepository.Add(utilisateur);
                    return RedirectToAction(nameof(Index));
                }
                return View(utilisateur);
            }
            catch
            {
                return View(utilisateur);
            }
        }

        // GET: UtilisateurController/Edit/5
        public ActionResult Edit(int id)
        {
            var utilisateur = _utilisateurRepository.GetById(id);
            if (utilisateur == null)
            {
                return NotFound();
            }

            return View(utilisateur);
        }

        // POST: UtilisateurController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Utilisateur utilisateur)
        {
            try
            {
                _utilisateurRepository.Update(utilisateur);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UtilisateurController/Delete/5
        public ActionResult Delete(int id)
        {
            var utilisateur = _utilisateurRepository.GetById(id);
            if (utilisateur == null)
            {
                return NotFound();
            }

            return View(utilisateur);
        }

        // POST: UtilisateurController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _utilisateurRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult UserBudgets()
        {
            int userId = Int32.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);

            var utilisateurBudgets = _utilisateurBudgetRepository.GetUtilisateurBudgetsByUserId(userId);
            var categorieUtilisateurBudgets = new Dictionary<int, List<CategorieUtilisateurBudget>>();
            var depensesListe = _mouvementRepository.GetByIdUser(userId);

            var depenses = 0.0;



            foreach (var budget in utilisateurBudgets)
            {
                var categories = _categorieUtilisateurBudgetRepository.GetCategorieUtilisateurBudgetsByUtilisateurBudgetId(budget.ID);
                categorieUtilisateurBudgets[budget.ID] = categories.ToList();
            }

            foreach (var depense in depensesListe)
            {
                depenses += depense.mouvement.montant;
            }

            var viewModel = new UserBudgetsViewModel
            {
                UtilisateurBudgets = utilisateurBudgets.ToList(),
                CategorieUtilisateurBudgets = categorieUtilisateurBudgets,
                depenses = depenses
            };

            return View(viewModel);
        }

        public IActionResult UserDepenses()
        {
            int userId = Int32.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);

            var utilisateurBudgets = _utilisateurBudgetRepository.GetUtilisateurBudgetsByUserId(userId);
            var categorieUtilisateurBudgets = new Dictionary<int, List<CategorieUtilisateurBudget>>();
            var depensesListe = _mouvementRepository.GetByIdUser(userId);

            var depenses = 0.0;



            foreach (var budget in utilisateurBudgets)
            {
                var categories = _categorieUtilisateurBudgetRepository.GetCategorieUtilisateurBudgetsByUtilisateurBudgetId(budget.ID);
                categorieUtilisateurBudgets[budget.ID] = categories.ToList();
            }

            foreach (var depense in depensesListe)
            {
                depenses += depense.mouvement.montant;
            }

            var viewModel = new UserDepensesViewModel
            {
                UtilisateurBudgets = utilisateurBudgets.ToList(),
                CategorieUtilisateurBudgets = categorieUtilisateurBudgets,
                Mouvements = (List<MouvementDetails>)depensesListe,
                depenses = depenses
            };
            viewModel.totalMontant = utilisateurBudgets.ToList().Sum(b => b.Montant);

            return View(viewModel);
        }
    }
}

PoketraVy-frontoffice/Views/Shared/ChangePassword.cshtml
@model PoketraVy_frontoffice.Models.ChangePasswordViewModel

@{
    ViewData["Title"] = "Change Password";
}

<h2>Change Password</h2>

<form asp-action="ChangePassword" method="post">
    <div class="form-group">
        <label asp-for="Username">Username</label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="NewPassword">New Password</label>
        <input asp-for="NewPassword" type="password" class="form-control" />
        <span asp-validation-for="NewPassword" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword">Confirm Password</label>
        <input asp-for="ConfirmPassword" type="password" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Change Password</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PoketraVy-frontoffice/Views/Shared/Login.cshtml
@model PoketraVy_frontoffice.Models.LoginViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <div class="text-center">
        <h1 class="display-4">Login</h1>

        <form asp-action="Login" method="post">
            <div class="form-group">
                <label asp-for="Username">Username</label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password">Password</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>

        <p>
            <a asp-action="ChangePassword" asp-controller="Authentication">Change Password</a>
        </p>
    </div>
</div>

PoketraVy-frontoffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PoketraVy_frontoffice</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-bank"></i> PoketraVy Frontoffice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    @if (User.Identity.IsAuthenticated)
                    {
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Utilisateur" asp-action="UserBudgets"><i class="bi bi-wallet2"></i> Budgets</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Utilisateur" asp-action="UserDepenses"><i class="bi bi-cash-coin"></i> Dépenses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CategorieUtilisateurBudget" asp-action="Create"><i class="bi bi-plus-circle-dotted"></i> Paramétrer budget</a>
                            </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <form id="logoutForm" asp-controller="Authentication" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link nav-link"><i class="bi bi-door-open"></i> Logout</button>
                            </form>
                        </li>
                    </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PoketraVy_frontoffice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>